### ISSUE TITLE
Paginating links and ordering

### ISSUE THREAD

**Issue by Nakort** [blakechambers/matterhorn#62] opened 2015-04-28 22:09 UTC
Add self, next, prev, first links to our current pagination interface,

if there is no next page, next should be null, same for prev.

```json
GET /articles.json

{
  "links": {
    "self"  : "http://example.org/articles?page=2",
    "next"  : "http://example.org/articles?page=3",
    "prev"  : "http://example.org/articles?page=1",
    "first" : "http://example.org/articles",
  },
  "data" : "..."
}
```

For endpoints that support ordering, links should be added for the different named orders.  For example:

```json

    GET /articles.json

    {
      "orders": {
        "oldest" : "http://example.org/articles?order=oldest",
        "recent" : "http://example.org/articles?order=recent",
      }
```

**Comment by blakechambers** [comment] 2015-05-04 17:12
This is a duplicate of #55.

**Closed** 2015-05-05 13:06 UTC
Labels: duplicate
